### ISSUE TITLE
Seek .pivotal-keys file and corellate with current git user email to set current api key

### ISSUE THREAD

**Issue by jasonm23** [jasonm23/story_branch#18]
Read from `./.pivotal-keys` (failover to `~/.pivotal-keys`) select a pivotal tracker api key, using the `user.email` setting in  `git --config` (checking `--local`, failover to `--global`) as a lookup key.

Also solve based on a `~/.pairs` / `.pairs` lookup (see [`git pair`]())

e.g.

```yaml
pivotal-keys:
  - initials: jm
    apikey: FAKEAPIKEYHERE
  - initials: dw
    apikey: FAKEAPIKEYHERE
```
